[package]
name = "libddupbak"
version = "0.1.0"
edition = "2021"

[lib]
name = "ddupbak"
crate-type = ["cdylib", "staticlib"]

[dependencies]
ddup-bak = { path = ".." }
ignore = "0.4.23"

[build-dependencies]
cbindgen = "0.24.0"
